name: Run Python Tests

on:
  push:
    branches:
      - master  # Trigger workflow on push to master branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to master branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    strategy:
      matrix:
        python-version: [3.8]  # Specify Python versions to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository's code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # Set up the specified Python version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt (if you have one)

      - name: Run tests
        run: |
          python ./test/maffin_testing.py  # Run your test file
